
name = "temp-email"
main = "src/worker.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
keep_vars = true
routes = [
  { pattern = "mail.pixapi.top/*", zone_name = "pixapi.top" }
]

[vars]
PREFIX = "tmp"
DEFAULT_DOMAINS = ["pixapi.top"]
DOMAINS = ["pixapi.top"]
JWT_SECRET = "pixapi_top_jwt_secret_20260704"
ADMIN_PASSWORDS = ["Pixapi2026mail"]
ENABLE_USER_CREATE_EMAIL = true
ENABLE_USER_DELETE_EMAIL = true

[[d1_databases]]
binding = "DB"
database_name = "temp_email"
database_id = "fcfcbeb3-0b22-417a-9cf6-1ddf6cb4214c"
